name: Release FAP

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Build with uFBT
        id: build
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          sdk-index-url: https://up.momentum-fw.dev/firmware/directory.json
          sdk-channel: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.build.outputs.fap-artifacts }}
          generate_release_notes: true
